const C={
  cm:{n:"ChenMo",r:"memory",f:"h"},jb:{n:"JiangBai",r:"villager",f:"h"},
  sw:{n:"SuWan",r:"villager",f:"h"},zs:{n:"ZhengShoushan",r:"villager",f:"h"},
  fh:{n:"FangHeng",r:"prophet",f:"g"},yz:{n:"YeZhiqiu",r:"witch",f:"g"},
  lx:{n:"LinXiaoman",r:"knight",f:"g"},ss:{n:"ShenShen",r:"magician",f:"g"},
  zy:{n:"ZhouYang",r:"wolf_king",f:"w"},gy:{n:"GuYan",r:"mech_wolf",f:"w"},
  tx:{n:"TangXiaotang",r:"hidden_wolf",f:"w"},zm:{n:"ZhaoMingcheng",r:"wolf",f:"w"}
};
const W=["zy","gy","tx","zm"];const V=["cm","jb","sw","zs"];
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function rm(a,i){return a.filter(x=>x!==i)}
function gs(){return {a:Object.keys(C),dd:[],wu:0,wr:0,kd:0,kl:0,kt:null,ms:[],pc:{},gss:null,zru:false};}
function wv(g){const aw=W.filter(w=>g.a.includes(w));if(!aw.length)return null;const vo={};aw.forEach(w=>{const ts=g.a.filter(i=>!W.includes(i));if(!ts.length)return;const sc={};const go={zy:"p",gy:"h",tx:"pr",zm:"s"}[w];ts.forEach(t=>{let s=20+Math.random()*30;if(go==="p"&&t==="lx")s+=20;if(go==="pr"){if(t==="cm")s-=80;if(t==="lx")s-=60;if(t==="sw")s+=30;}if(go==="s"){if(V.includes(t))s+=20;if(t==="zs")s+=30;}sc[t]=s;});vo[w]=Object.entries(sc).sort((a,b)=>b[1]-a[1])[0][0];});const tl={};aw.forEach(w=>{const t=vo[w];tl[t]=(tl[t]||0)+1;});const mv=Math.max(...Object.values(tl));const top=Object.entries(tl).filter(([_,x])=>x===mv).map(([k])=>k);return{target:pick(top),detail:vo};}
function wa(g,wt){const tot=g.wu+g.wr;if(tot>=3)return{};if(Math.random()<0.65&&g.wr<3)return{a:"r",t:wt};if(Math.random()<0.05&&g.wu<3){const c=g.a.filter(i=>i!=="yz"&&!W.includes(i));if(c.length)return{a:"c",t:pick(c)};}return{};}
function pr(g){const o=g.a.filter(i=>i!=="fh");if(!o.length)return null;const uc=o.filter(i=>!g.pc[i]);const t=uc.length?pick(uc):pick(o);const ch=C[t];g.pc[t]=ch.r==="hidden_wolf"?"a":(ch.f==="w"?"e":"a");return{t,r:g.pc[t]};}
function kn(g){if(g.kd>0)return{a:"r"};const su=g.a.filter(i=>!W.includes(i)&&i!=="lx");if(!su.length)return{a:"n"};if(Math.random()<0.12){let t;if(g.a.includes("tx")&&Math.random()<0.35){const nc=su.filter(s=>s!=="cm"&&s!=="lx");t=nc.length?pick(nc):pick(su);}else t=pick(su);return{a:"d",t,s:C[t].f==="w"};}if(Math.random()<0.35){const ts=g.a.filter(i=>i!=="lx"&&!W.includes(i));if(ts.length){const wk=ts.filter(t=>V.includes(t)||t==="yz");return{a:"g",t:wk.length?pick(wk):pick(ts)};}}return{a:"n"};}
function mg(g){const o=g.a.filter(i=>i!=="ss");if(o.length<2)return{a:"n"};const b=g.ms||[];const e=o.filter(i=>!b.includes(i));if(e.length<2)return{a:"n"};const sh=[...e].sort(()=>Math.random()-0.5);return{a:"s",p:[sh[0],sh[1]]};}
function fj(g,d){if(!g.a.includes("tx")||d<2)return null;if(Math.random()<0.18){const t=pick(g.a.filter(i=>i!=="tx"&&i!=="cm"));return{t,c:"e"};}return null;}
const EV=["locked drawer","food argument","window found open","footprints in snow","crying heard","broken lantern","old newspapers"];
function sim(sd){let s=sd;function rng(){s=(s*16807)%2147483647;return(s-1)/2147483646;}const g=gs();const log=[];for(let d=1;d<=7;d++){const dl=[];if(d>1&&Math.random()<0.6)dl.push("[EVT] "+pick(EV));const j=fj(g,d);if(j)dl.push("[悍跳]TX->"+C[j.t].n);const k=kn(g);if(k.a==="d"){if(k.s){dl.push("[骑士]击杀"+C[k.t].n+"(狼)");g.a=rm(g.a,k.t);g.dd.push(k.t);g.kd=2;}else{dl.push("[骑士]误杀"+C[k.t].n+"(好人)");g.a=rm(g.a,k.t);g.dd.push(k.t);g.kd=3;}}else if(k.a==="g"){g.kl=true;g.kt=k.t;dl.push("[守卫]守护"+C[k.t].n);}else{if(g.kd>0){g.kd--;if(g.kd>0)dl.push("[骑士]虚弱"+g.kd);}g.kl=false;}const p=pr(g);if(p)dl.push("[预言家]查验"+C[p.t].n+":"+(p.r==="a"?"盟友":"敌人"));const m=mg(g);if(m.a==="s"){g.ms=[...m.p];dl.push("[魔术师]交换"+C[m.p[0]].n+"X"+C[m.p[1]].n);}log.push("D"+d);dl.forEach(e=>log.push("  "+e));const nl=["N"+d];const w=wv(g);if(!w){log.push("  狼全灭");log.push("");break;}let at=w.target;const sp=g.ms||[];if(sp.length===2&&g.a.includes("ss")){if(sp.includes(w.target)&&rng()<0.5){const o=sp.find(i=>i!==w.target);at=o;nl.push("[魔术师]狼迷->"+C[o].n);}}g.ms=[];const vd=Object.entries(w.detail).map(([k,v])=>C[k].n+"->"+C[v].n).join();nl.push("[狼]"+vd);let guard=false;if(g.kt&&g.kl){guard=g.kt===at;g.kt=null;}const wx=wa(g,at);let saved=false;if(wx.a==="r"){if(guard){nl.push("[W+G]冲突,"+C[at].n+"死");g.wr++;}else{nl.push("[女巫]救"+C[at].n);g.wr++;saved=true;}}else if(wx.a==="c"){nl.push("[女巫]诅咒"+C[wx.t].n);g.wu++;}if(!saved&&!guard){const ch=C[at];g.a=rm(g.a,at);g.dd.push(at);nl.push("[死亡]"+ch.n);if(ch.r==="wolf_king"&&!g.zru){g.zru=true;const ow=W.filter(w=>w!==at&&g.a.includes(w));if(ow.length){const tk=pick(ow);g.a=rm(g.a,tk);g.dd.push(tk);nl.push("[狼王]带走"+C[tk].n);}}if(g.a.includes("gy")&&!g.gss){const rr=C[at].r;if(["prophet","witch","knight","magician"].includes(rr)){g.gss=rr;nl.push("[机械狼]抢"+ch.n+":"+rr);}}}if(g.a.includes("zm"))nl.push("[清道夫]清理");const tu=g.wu+g.wr;if(tu>0)nl.push("[女巫]"+tu+"/3");nl.forEach(e=>log.push("  "+e));log.push("");const al=g.a.filter(i=>!W.includes(i)).length;if(d>=7)return{o:al>0?"DAY7":"WIPE",ds:7,dd:g.dd,a:g.a,l:log};}return{o:"TIMEOUT",ds:7,dd:g.dd,a:g.a,l:log};}
const R=[];for(let i=0;i<20;i++)R.push(sim(i+1));const S={d7:0,wi:0,ad:0,fh:0,yz:0,lx:0,ss:0,cm:0,sw:0,jb:0,zs:0};R.forEach(r=>{r.o==="DAY7"?S.d7++:S.wi++;S.ad+=r.ds;if(r.dd.includes("fh"))S.fh++;if(r.dd.includes("yz"))S.yz++;if(r.dd.includes("lx"))S.lx++;if(r.dd.includes("ss"))S.ss++;if(r.dd.includes("cm"))S.cm++;if(r.dd.includes("sw"))S.sw++;if(r.dd.includes("jb"))S.jb++;if(r.dd.includes("zs"))S.zs++;});S.ad=(S.ad/20).toFixed(1);
console.log("=== 无尽雪夜v2 叙事友好版 ===");console.log("结局: DAY7="+S.d7+" 全灭="+S.wi+" 平均="+S.ad+"d");console.log("");console.log("方衡:"+S.fh+" 叶知秋:"+S.yz+" 林小满:"+S.lx+" 沈慎:"+S.ss);console.log("陈默:"+S.cm+" 苏晚:"+S.sw+" 江白:"+S.jb+" 郑守山:"+S.zs);console.log("");
for(let i=0;i<20;i++){const r=R[i];console.log("R"+(i+1)+"|"+r.o+"|d"+r.ds);console.log("活:["+r.a.map(id=>C[id].n).join()+"]");console.log("死:["+r.dd.map(id=>C[id].n).join()+"]");r.l.forEach(l=>{if(l.startsWith("  ["))console.log(l);});console.log("");}